name = Simple
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = simple-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[slider]         = Slider
regions[navigation_text]= Navigation text
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[footer_pre]     = Pre Footer


; Stylesheets
stylesheets[all][] = css/layouts/simple/simple.layout.css
