<?php

/*
 * For cannhealth , we have 2 enviroment
 * distributor | users | and one extra visitors
 *
 * if I arrive to website from external site , I see the website like a user normal
 *
 * */

//VALIDATE AUTENTICATED USER AND USER TYPE SESSION

define('DISTRIBUTOR', 'distributor');
define('USER', 'client');
define('FRONTPAGE_URL', 'home');

function cann_general_permission()
{
    return array
    (
        'administer my panel manager' => array
        (
            'title' => t('Administer my panel manager'),
            'description' => t('Perform administration tasks for my panel manager.'),
        ),
        'You can buy medical mariahuana' => array
        (
            'title' => t('You can buy mariahuana medical'),
            'description' => t('You can buy mariahuana medical'),
        ),

    );
}

function cann_general_init()
{

  //drupal_add_css("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css",["type"=>"external"]);

    drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/json2/20121008/json2.js', 'external');
    drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js', 'external');
    drupal_add_js('//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.0/backbone-min.js', 'external');

$url = $_GET['q'];
    //cann_health_clean_session_type();

    //NOTICE IF WE TRY TO ENTRY to home  and we've already choose one option
    if( $url == 'home' && in_array($_SESSION['user_type'], [ USER , DISTRIBUTOR] ) ){
        drupal_goto($_SESSION['user_type']);
        exit();

    }

    // if I'm trying to entry by distributor or user url and this is not my session
    //I will redirect to home or my selected section before
    if( in_array($url , [ USER , DISTRIBUTOR] ) &&  $_SESSION['user_type'] != $url ){
        drupal_goto('home');
        exit();
    }

//    drupal_set_message(   $_SESSION['user_type']  . ' ('.$url.')' );
    //dpm($_SESSION['buylist']);

}

function cann_general_process_page(&$var)
{



}


function cann_general_menu(){

    // to clean the session
    $items['clean_session'] = array(
        'title' => 'CannHealth',
        'page callback' => 'cann_general_page_clean_session_type',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    //front page site
    $items['home'] = array(
        'title' => 'CannHealth',
        'page callback' => 'cann_general_page_home',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    //redirect by session type
    $items['register'] = array(
        'title' => '',
        'page callback' => 'cann_general_register_redirect',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    // marihuana users home page
    $items[USER] = array(
        'title' => 'Registered Medical Mariahuana Users ',
        'page callback' => 'cann_general_page_home',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items[USER . '/register'] = array(
        'title' => 'Register',
        'page callback' => 'cann_general_page_client_register',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    //producers home page
    $items['distributor'] = array(
        'title' => 'Licenced Distributors',
        'page callback' => 'cann_general_page_home',
        'access callback' => 'cann_general_page_home_distributor_access',
        'type' => MENU_CALLBACK,
    );

    $items['distributor/register'] = array(
        'title' => 'Register',
        'page callback' => 'cann_general_page_distributor_register',
        'access callback' => 'cann_general_page_home_distributor_access',
        'type' => MENU_CALLBACK,
    );

    $items['panel'] = array(
        'title' => 'My Panel Manager',
        'page callback' => 'cann_general_page_panel_manager',
        'access arguments' => array('administer my panel manager'),
        'type' => MENU_CALLBACK,
    );

    $items['panel/transactions'] = array(
        'title' => 'Manage your Transactions',
        'page callback' => 'cann_general_page_panel_transaction',
        'access arguments' => array('administer my panel manager'),
        'type' => MENU_CALLBACK,
    );

    $items['panel/order-history'] = array(
        'title' => 'Order History',
        'page callback' => 'cann_general_page_order_history',
        'access arguments' => array('administer my panel manager'),
        'type' => MENU_CALLBACK,
    );

    $items['panel/products'] = array(
        'title' => 'Manage your Products',
        'page callback' => 'cann_general_page_panel_product_list',
        'access arguments' => array('administer my panel manager'),
        'type' => MENU_CALLBACK,
    );



    $items['panel/products/add'] = array(
        'title' => 'Manage your Products',
        'page callback' => 'cann_general_page_panel_product_add',
        'access arguments' => array('administer my panel manager'),
        'type' => MENU_CALLBACK,
    );
    $items['panel/products/%/edit'] = array(
        'title' => 'Edit your Products',
        'page callback' => 'cann_general_page_panel_product_edit',
        'page arguments' => array(2),
        'access arguments' => array('administer my panel manager'),
        'type' => MENU_CALLBACK,
    );
    $items['panel/products/%/publish'] = array(
        'title' => '',
        'page callback' => 'cann_general_page_panel_product_edit_status',
        'page arguments' => array(2),
        'access arguments' => array('administer my panel manager'),
        'type' => MENU_CALLBACK,
    );
    //using in block http://cannhealth.dev/admin/structure/block/manage/block/1/configure
    $items['define-type/%'] = array(
        'title' => '',
        'page callback' => 'cann_general_page_define_type',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    //RUTAS PARA COMPRAS
    $items['buy/add/%'] = array(
        'title' => '',
        'page callback' => 'cann_general_buy_add',
        'page arguments' => array(2),
        'access arguments' => array('You can buy medical mariahuana'),
        'type' => MENU_CALLBACK,
    );

    $items['checkout/remove/%'] = array(
        'title' => '',
        'page callback' => 'cann_general_buy_remove',
        'page arguments' => array(2),
        'access arguments' => array('You can buy medical mariahuana'),
        'type' => MENU_CALLBACK,
    );

    $items['checkout'] = array(
        'title' => 'My List Products',
        'page callback' => 'cann_general_page_checkout',
        'access arguments' => array('You can buy medical mariahuana'),
        'type' => MENU_CALLBACK,
    );

    return $items;

}



function cann_general_register_redirect(){

    if(empty($_SESSION['user_type'])){
        drupal_goto('home');
    }else{
        drupal_goto($_SESSION['user_type'].'/register');
    }


}


function cann_general_page_home_distributor_access(){

    if($_SESSION['user_type'] == DISTRIBUTOR ){
        return true;
    }else{
        return false;
    }

}


//CREATE ENVIROMENT OF THE FIRST PAGE
//THIS PAGE IS FILLED WITH CUSTOM BLOCKS
function cann_general_page_home(){
    return '';
}


function cann_general_page_define_type($type){
/*
 * Exist 2 types : DISTRIBUTOS AND USER
 * */

   if(!$type){
    drupal_goto('home');
    exit();
   }
    $_SESSION['user_type'] = $type;

    drupal_goto('home');

    return '';
}

function cann_health_clean_session_type(){
    unset($_SESSION['user_type']);
}

function cann_general_page_clean_session_type(){
    cann_health_clean_session_type();
    drupal_goto(FRONTPAGE_URL);
}

function cann_general_page_distributor_register(){

    $tpl = '';
    $tpl = @render(drupal_get_form('cann_general_page_distributor_register_form'));


    return $tpl;
}

function cann_general_page_distributor_register_form($node, &$form_state){


    $form['producer_name'] = array(
        '#type' => 'textfield',
        '#title' => 'Licenced Producer Name',
        '#default_value' =>'',
        '#required' => TRUE,

    );
    $form['main_contact'] = array(
        '#type' => 'textfield',
        '#title' => 'Main Contact',
        '#default_value' =>'',
        '#required' => TRUE,

    );

    $form['website'] = array(
        '#type' => 'textfield',
        '#title' => 'Web Site',
        '#default_value' =>'',
        '#required' => TRUE,
    );

    $form['phone'] = array(
        '#type' => 'textfield',
        '#title' => 'Phone Number',
        '#default_value' =>'',
        '#required' => TRUE,
    );

    $form['fax'] = array(
        '#type' => 'textfield',
        '#title' => 'Fax Number',
        '#default_value' =>'',
        '#required' => TRUE,
    );

    $form['address'] = array(
        '#type' => 'textfield',
        '#title' => 'Address',
        '#default_value' =>'',
        '#required' => TRUE,
    );

    $form['mail'] = [
        '#type' => 'textfield',
        '#title' => 'Email Address',
        '#default_value' =>'',
        '#required' => TRUE,
    ];

    $form['upload'] = array(
        '#type' => 'file',
        '#title' => 'Upload Licenced Document',
    );

    $form['#attributes'] = ['enctype' => "multipart/form-data"];
    $form['#validate'][] = 'cann_general_page_distributor_register_form_validate';
    $form['submit'] = array('#type' => 'submit', '#value' => t('REGISTER') );

    return $form;

}

function cann_general_page_distributor_register_form_validate(&$form, &$form_state)
{
    //VALIDANDO SUBIR FILE
    $file = file_save_upload('upload', array());
    // If the file passed validation:
    if ($file) {
        // Move the file into the Drupal file system.
        if ($file = file_move($file, 'public://'.date("Y/m/d"))) {
            // Save the file for use in the submit handler.
            $form_state['storage']['file'] = $file;
        }
        else {
            form_set_error('file', t("Failed to write the uploaded file to the site's file folder."));
        }
    }
    else {
        form_set_error('file', t('No file was uploaded.'));
    }


}


function cann_general_page_distributor_register_form_submit($form, &$form_state) {


    //VALIDANDO FILE SUBIDO PERMANTENE
    $file = $form_state['storage']['file'];
    // We are done with the file, remove it from storage.
    unset($form_state['storage']['file']);
    // Make the storage of the file permanent.
    $file->status = FILE_STATUS_PERMANENT;
    // Save file status.
    file_save($file);
//    dpm($file);
    $file->display = 1;
    $file->description = "";


    $roles = array(2 => true, 4 => true);
    $new_user = array(
        'name' => $form_state['values']['producer_name'],
        'pass' => user_password(),
        'mail' => $form_state['values']['mail'],
        'init' => $form_state['values']['mail'],
        'field_dist_licenced' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['producer_name']))),
        'field_dist_main_contact' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['main_contact']))),
        'field_dist_website' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['website']))),
        'field_phone_number' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['phone']))),
        'field_dist_fax_number' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['fax']))),
        'field_adress' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['address']))),
        'field_dist_upload_licenced' => array(LANGUAGE_NONE => array( (array)$file )),
        'status' => 0,
        'access' => REQUEST_TIME,
        'roles' => $roles,
    );
// $account returns user object
    $account = user_save(null, $new_user);

    //NOTIFICATION TO ADMINISTRATORS
    //NOTIFICATION TO CLIENT.

//    dpm($account);
    //VALIDANDO ERRORES
    //YA EXISTE EMAIL DE USUARIO



    //Redireccion
    drupal_goto("home");
    drupal_set_message("Thank you for registering");
}



function cann_general_form_alter(&$form, $form_state, $form_id)
{

    if (in_array($form_id, array('user_login', 'user_login_block')))
    {
        $field_extra['code_id'] = array(
            '#type' => 'textfield',
            '#title' => 'Code ID',
            '#default_value' =>'',
            '#required' => TRUE,
            '#attributes' => array('tabindex' => 1),
            '#weight'=>-10
        );

        $form = $form + $field_extra;

        array_unshift($form['#validate'], 'cann_general_form_user_login_validate');

    }
//    var_dump($form);

}

function cann_general_form_user_login_validate(&$form, $form_state)
{
//    dpm($form_state);
//    drupal_set_message('cann_general_form_user_login_validate() called', 'status');

    $user = user_load_by_name($form_state['values']['name']);

    if(!$user)
    {
        form_set_error('name', "User doesn't exist! ");
    }
    elseif($user->name == 'admin')
    {
        // pass
    }
    else
    {
        if($user->field_code_id['und'][0]['value'] != $form_state['values']['code_id'])
        {
            form_set_error('code_id', "Code ID is wrong or not exist");
        }
    }

}

function cann_general_user_login(&$edit,$account)
{
//    drupal_set_message('cann general user login');
//    dpm($account);
//    dpm($edit);

    $roles = $account->roles;
    if($roles['4'])
    {
        $_SESSION['user_type'] = DISTRIBUTOR;
    }
    elseif($roles['5'])
    {
        $_SESSION['user_type'] = USER;
    }

}


function cann_general_user_logout($account)
{
//    drupal_set_message('cann general user logout');
//    dpm($account);
    cann_health_clean_session_type();


}


function cann_general_page_panel_manager()
{
    return "";

}

// list of products by autenticated users
function cann_general_page_panel_product_list()
{
    $tpl = '';
//    $tpl .= "<h2>Manage your products</h2>";
    $tpl .= "<div class='actions-link'><a class='delete' href='/panel/products/delete-multiple'>Delete</a><a class='add' href='/panel/products/add'>New Product</a></div>";

    $tpl .= render(drupal_get_form('cann_general_page_panel_product_list_form'));


    return $tpl;
}


function cann_general_page_panel_product_list_form($node, &$form_state)
{
    $limit = 10;
    global $user;

    $header = array(
        array('data' => t('ID'), ), // sort
        array('data' => t('Product Name'), ),
        array('data' => t('Action')),
        array('data' => t('Edit'), ),
    );

    //query
    $query = db_select('node', 'n');

    $query->fields('n',['nid','title','status'] );
    // $query->addExpression("CONCAT(g.code, '-', g.id)", 'codefull');
    $query->condition('n.uid', $user->uid , '=');

    $table_sort = $query->extend('TableSort') // Add table sort extender.
        ->orderByHeader($header); // Add order by headers.


    $pager = $table_sort->extend('PagerDefault')
        ->limit($limit); // 5 rows per page.

    $result = $pager->execute();

    $rows = array();
    foreach($result as $res){

        switch ($res->status) {
            case '0':
                $status_label = "Not Published";
                break;
            case '1':
                $status_label = "Published";
                break;
        }




        $rows[$res->nid] = array(
            $res->nid,
            $res->title,
            "<a class='action-link $status_label' href='/panel/products/".$res->nid . "/publish' >".$status_label."</a>",
            "<a class='action-link edit' href='/panel/products/".$res->nid . "/edit' >Edit item</a>",
            );

    }


    $form['table'] = array(
        '#type' => 'tableselect',
        '#header' => $header,
        '#options' => $rows,
        '#empty' => t('Table has no row!')
    );

    $form['pager'] = array('#markup' => theme('pager'));

    return $form;


}


//page when you can create new products
function cann_general_page_panel_product_add()
{
    global $user;
    $block = array();
    module_load_include('inc', 'node', 'node.pages');
    $node = (object) array(
        'uid' => $user->uid,
        'name' => (isset($user->name) ? $user->name : ''),
        'type' => 'product',
        'language' => LANGUAGE_NONE,
        'ajax_form' => '1');

    $form = drupal_get_form('product' . '_node_form', $node);
    $page = render($form);

    return $page;
}

function cann_general_page_panel_product_edit($nid)
{
    $producto = node_load($nid);
    module_load_include('inc', 'node', 'node.pages');
    $form = drupal_get_form('product' . '_node_form', $producto);
    $page = render($form);

    return $page;

}

function cann_general_page_panel_product_edit_status($nid)
{

    $producto = node_load($nid);
    $producto->status = !$producto->status;
    node_save($producto);

    drupal_goto("panel/products");
}

function cann_general_page_client_register()
{
    $tpl = '';
    $tpl = @render(drupal_get_form('cann_general_page_client_register_form'));


    return $tpl;
}

function cann_general_page_client_register_form($node, &$form_state){


    $form['first_name'] = array(
        '#type' => 'textfield',
        '#title' => 'First Name',
        '#default_value' =>'',
        '#required' => TRUE,

    );
    $form['last_name'] = array(
        '#type' => 'textfield',
        '#title' => 'Last Name',
        '#default_value' =>'',
        '#required' => TRUE,
    );

    $form['phone'] = array(
        '#type' => 'textfield',
        '#title' => 'Phone Number',
        '#default_value' =>'',
        '#required' => TRUE,
    );



    $form['address'] = array(
        '#type' => 'textfield',
        '#title' => 'Address',
        '#default_value' =>'',
        '#required' => TRUE,
    );

    $form['mail'] = [
        '#type' => 'textfield',
        '#title' => 'Email Address',
        '#default_value' =>'',
        '#required' => TRUE,
    ];


    $form['submit'] = array('#type' => 'submit', '#value' => t('REGISTER') );

    return $form;

}

function cann_general_page_client_register_form_submit($form, &$form_state) {

    $roles = array(2 => true, 5 => true);

    $new_user = array(
        'name' => $form_state['values']['first_name'],
        'pass' => user_password(),
        'mail' => $form_state['values']['mail'],
        'init' => $form_state['values']['mail'],
        'field_first_name' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['first_name']))),
        'field_last_name' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['last_name']))),
        'field_phone_number' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['phone']))),
        'field_adress' => array(LANGUAGE_NONE => array(array('value' => $form_state['values']['address']))),
        'status' => 0,
        'access' => REQUEST_TIME,
        'roles' => $roles,
    );
// $account returns user object
    $account = user_save(null, $new_user);

    //NOTIFICATION TO ADMINISTRATORS
    //NOTIFICATION TO CLIENT.
    $deb = 1;
    drupal_goto($_SESSION['user_type']);
    drupal_set_message("Thank you for registering");
}


function cann_general_block_info() {

    $blocks['user_type'] = array(
        'info' => t('User type'),
    );

    $blocks['user_type_home'] = array(
        'info' => t('User type home'),
    );

    $blocks['user_navigation'] = array(
        'info' => t('User type navigation'),
    );

    $blocks['user_name'] = array(
        'info' => t('User name'),
    );

    $blocks['chekcout_top'] = array(
        'info' =>'checkout top',
    );
    $blocks['chekcout_sidebar'] = array(
        'info' =>'checkout sidebar',
    );

    return $blocks;
}

function cann_general_block_view($delta='') {
    $block = array();
    switch ($delta) {
        case 'user_type':
            $block['subject'] = t('User type top');
            $block['content'] = cann_general_block_user_type_content();
            break;
        case 'user_type_home':
            $block['subject'] = t('User type Home');
            $block['content'] = cann_general_block_user_type_home_content();
            break;
        case 'user_navigation':
            $block['subject'] = t('User type navigation');
            $block['content'] = cann_general_block_user_navigation_content();
            break;
        case 'user_name':
            $block['subject'] = t('User name');
            $block['content'] = cann_general_block_user_name_content();
            break;
        case 'chekcout_top':
            $block['subject'] = t('checkout top');
            $block['content'] = cann_general_block_checkout_top_content();
            break;
        case 'chekcout_sidebar':
            $block['subject'] = t('checkout sidebar');
            $block['content'] = cann_general_block_checkout_sidebar_content();
            break;
    }
    return $block;
}

//campo dentro del full producto
function cann_general_field_boton_comprar(){


    $nid = arg(1);

    $html='';
    $en_lista = cann_general_search_item_buy($nid);

    if($en_lista)
    {//si ya esta seleccionado
        $html = "<div class='comprar-field'>
    <span class='remove'><a href='/buy/remove/$nid'>Remove</a></span>
    <span class='go-checkout'><a href='/checkout'>Go to Checkout</a></span>
    <span class='continue'><a href='/products'>Continue shopping</a></span>
    </div>";

    }else
    {//si no esta seleccionado
    $html = "<div class='comprar-field'>
    <span class='libre'>
        <a href='/buy/add/$nid'>BUY THIS PRODUCT</a>
    </span>
    </div>";

    }





    return $html;
}

function cann_general_block_checkout_top_content()
{

    $items = cann_general_buy_items_cantidad();
    $block = "
    <div class='content top'>
        <div class='nitems'>Your Items (<span>$items</span>)</div>
        <div class='link'><a href='/checkout'>Reserve Now</a> </div>
    </div>
    ";

    return $block;

}

function cann_general_block_checkout_sidebar_content()
{
    $items = cann_general_buy_items_cantidad();
    $block = "
    <div class='buy sidebar'>
        <div class='nitems'>Your Items (<span>$items</span>)</div>
        <div class='link'><a href='/checkout'>Reserve Now</a> </div>
    </div>
    ";

    return $block;
}

function cann_general_block_user_name_content()
{
    global $user;
//    dpm($user);
    $block = "<div class='user_name'><span class='label'>User:</span><span class='name'>".$user->name."</span></div> ";

    return $block;
}

function cann_general_block_user_type_content(){
    $block = '';

    global $user;

    //SI ESTA LOGEADO NO MUESTRA NADA
    if(isset($user) && !empty($user->uid))
        return "";

    if(empty($_SESSION['user_type']) || $_SESSION['user_type']== USER )
        $block = "<span class='distributor'>Are you a Licenced Distributor? <a href='/define-type/".DISTRIBUTOR."'>Click Here</a></span>";
    else
        $block = "<span class='client'>Are you a Marihuana Medical User? <a href='/define-type/".USER."'>Click Here</a></span>";
    return $block;
}
function cann_general_block_user_type_home_content()
{
    $block = "
    <div class='logo'></div>
    <div class='user_type'>
        <div class='type first'> Licenced<br>Producer/Distributors<br><a href='/define-type/".DISTRIBUTOR."'>Click Here</a></div>
        <div class='type last'> Registered Medical<br>Marihuana Users<br><a href='/define-type/".USER."'>Click Here</a></div>
    </div>
    ";
    return $block;
}

//MUESTRA EL MENSAJE EN EL LISTO DE COLOR ROJO O VERDE
function cann_general_block_user_navigation_content()
{
    //POR DEFECTO MUESTRA EL TITULO
    $info = "<div class='listo text'>" . drupal_get_title() . "</div>";

    //PERSONALIZACION POR URL
    $url = $_GET['q'];
//    dpm($url);
    if($url == 'user')
    {
        $info = 'Log In';
    }elseif($url == 'products' )
    {
        $info .= "<div class='liston sub-text'>Online ordering will be available within Canada for registered Client</div>";
    }elseif($url=='checkout')
    {
        $info = "Checkout";
    }



    //RETORNAL ALA VARIABLE INFO QUE CONTENIENE EL TITULO COMO HTML
    return $info;
}


function cann_general_preprocess_page(&$vars)
{
    $url = $_GET['q'];

    if(!$vars['logged_in'] &&  $url == 'user' )
    {
        drupal_set_title("Login or <a class='link-register' href='/register'>Register</a>",PASS_THROUGH);
    }

}

//devuelve si existe o no en la lista de compra
function cann_general_search_item_buy($nid)
{
    if(in_array( $nid , $_SESSION['buylist'] ))
        return true; //ya existe
    else
        return false; // no existe

}

function cann_general_buy_add($nid)
{
    $existe = cann_general_search_item_buy($nid);
    if(!$existe)
        $_SESSION['buylist'][$nid] = $nid;

    drupal_goto('node/'.$nid);

}

function cann_general_buy_remove($nid)
{

    unset($_SESSION['buylist'][$nid]);
    drupal_goto('checkout');

}

function cann_general_buy_items_cantidad()
{
    return count($_SESSION['buylist']);
}

function cann_general_page_checkout()
{
    $html = "
    <table class='t-checkout'>
        <tr>
            <th></th>
            <th>PRODUCTS</th>
            <th>GRAMS</th>
            <th>PRICE</th>
            <th></th>
            <th>TOTAL</th>
            <th></th>
        </tr>";
    if(!count($_SESSION['buylist']))
    {
     $html = "<tr colspan='7'><td><a href='/products'>Continue shopping</a></td></tr>";
    }else
    {
        $items = $_SESSION['buylist'];
        $total_final = 0;
        foreach($items as $nid)
        {
            $html .="<tr>";
            $product = node_load($nid);

            $initial_grams = 1;

            $pic= theme('image_style', array('path' => $product->field_image['und'][0]['uri'], 'style_name' => "thumb_product" ));
            $title = $product->title;
            $producer = "<label>Producer: </label>".$product->name;
            $field_grams = "<input type='text' value='$initial_grams'>";
            $price = $product->field_price['und'][0]['value'];
            $total = $initial_grams * $price;
            $total_final += $total;
            $remove = "<a href='/checkout/remove/$nid' class='check-remove'>*</a>";

            $html .="
                <td class='pic'>$pic</td>
                <td>
                    <div class='descript'>
                        <div>$title</div>
                        <div class='producer'>$producer</div>
                    </div>
                </td>
                <td class='grams'>    $field_grams   </td>
                <td class='price' data-price='$price'>$   $price   </td>
                <td class='sub-total' data-subtotal='$total'>$ $total   </td>
                <td class='link-remove'>$remove</td>

            ";

            $html .="</tr>";

        }

        $html .="<tr class='total'><td colspan='4'></td><td>TOTAL</td><td><span class='check-total'>$ $total_final</span></td></tr>";
    }

    $html .= "</table>";

    $html .= "<button class='btn_checkout'>Checkout</button>";



    return $html;


}


function cann_general_page_panel_transaction()
{
    return "";
}

function cann_general_page_order_history()
{
    return '';
}

